---
title: Comments on Reconstructions of Ballet Classics
authors:
  - name: Montaque Reynolds
    affiliation: Stetson University
    roles: writing
    corresponding: true
bibliography: ["./../../Un-Duplicates.bib", "./../../references.bib"]
---

Professor Van Camp asks how should the contemporary dance community assess the authenticity of classical ballet reconstructions? There are two important possibilities, one includes the work's musical notations, while we might also consider the work's text or story [@vanunpublisheddraft, 1]. The distinction here is between two features of the work. First, there is the work's syntax, akin to its grammatical structure. Here we would assess the authenticity of a dance by looking at its notational structure, music or dance scores, rehearsal notes, drawings, published criticisms etc. On the other hand we would consider its semantics, or narrative meaning.

Using the definition offered by Mark @fran17 in his introduction to the Oxford handbook of dance and reenactment, reconstructions are preservations of past accomplishments. On one hand, the meaning of the work might be seen as a past accomplishment. On the other hand, reenactments aim to reimagine the past performances. However, it is not yet clear whether reenactments aim to reimagine the past performances of a work, or the historical meaning behind the work.

> “reenactment encompasses the theatrical and dramaturgical devices with which the effect of the dance as a representation of itself in the past is shaped and manifested in performance.” [@fran17, 8].

On this later point, it would appear that there are many important reasons for re-imagining a ballet performance. For one, if we do not have an authentic historical item from a particular time period to include in a museum collection from that time period, it may make sense to use the nearest counterpart. Analogously however, the 19th century ballet performances of *Swan Lake*, *Giselle* and *The Sleeping Beauty* are thought to be authentic versions of the original, even though we do not have relevant dance notations of their original performances. In her discussion of *Swan Lake* by Ratmansky, Professor Van Camp notes that though Ratmansky's is the *closest* to the original performance, opting to use costumes similar to those the original conservative audiences would have seen, it was not as well received as we might have thought it would be. Professor Van Camp notes that this is because it does not have the aesthetic appeal necessary to generate interests from modern audiences. Modern dances are more athletic than the original dancers would have been, as modern costuming reflects this appeal featuring shorter tutus that show off more of the muscular features of the dancers.

As such, it is not clear that a "nearest counterpart" is necessary since it is largely thought that we have the originals already. One important direction of consideration here, is that an important part of the essence of a performance, apart from its compliance with either a music or dance score, would instead be the emotional essence of 1) the original performance, or 2) the emotional essence conceived of by the creator of that work, or 3a) social factors surrounding the public reception of the performance, or 3b) social factors of which the piece provides a commentary on.

For instance, @luka77 argues that a work's emotional essence is produced by social factors. What he has in mind is in part the aesthetic movement in modern dance from realism to expressionism. The original Swan Lake would have produced a particular emotional essence. As such, we might think that one target of reconstruction is this particular emotional essence. Arguably, when it comes to the emotional essence of a given performance, it is not clear that here too, how we determine if a performance has captured the emotional essence of the original performance.

Perhaps the closest terms we have for this distinction in the reenactment and reconstruction literature, is what Andrew @kani24 attributes to Julian @dodd20; 'compliance' authenticity versus *'interpretive'* authenticity. First, Professor Van Camp carefully and expertly draws out the complications for understanding why this is a hard problem. In three prominent examples of the reconstructions of the 19th century pieces, ***Swan Lake***, ***Giselle***, and ***Sleeping Beauty***, if we focus on audience reactions to these pieces, then the 'reconstructions' do not appear to have been as appealing as their 19th century reenactment counterparts since audience favor typically follows works that reimagine classics. This later position is explored with more detail in a review written by Professor Van Camp explaining the loose requirements for authenticity in ballet reenactments versus those of reconstructions, usually focus on a shift of social values.

Tamara Rojo as the artistic director for the San Francisco Ballet delicately introduces variations in her version of *Raymonda* by "expunging Middle Eastern stereotypes" and exploring new forms of agency by introducing a female heroine rather than a male hero. This shows the tolerance ballet has for variation without loss of ontological identity. But this may also just mean that a work's ontological identity is grounded somewhere else.

Professor Van Camp defends these loose standards as authentically derivative since often times our own standards are amenable to change in other areas, such as values which we know have strong emotive force. A central question here then could be the shifting plasticity of standards and how these diverge between reconstructions and reenactments. This is especially important if we consider whether there is a more ultimate and underlying truth at which multiple performances of a work may attempt to reveal. At the Paris 1913 premier of *Le Sacre du Printemps* staged by Vaslav Nijinsky, it is said that the audience rioted owing to the near primal movements of the performers.

In 2009, the resident choreographer for the Boston Ballet premiered a version of *Le Sacre du Printemps* that diverged from Nijinsky's "uncontrolled and raw movements" with the introduction of "clean shapes, intricate isolations, and dynamic partner work". Elo defends his interpretation arguing that highlighting the performances universal value of "community, identity, and social systems" did not require the "sacrifice for the common good" that it required when Nijinsky staged the work in 1913. This is important considering the role the performance played in moving the theater into the modern era of ballet.

But this also leads to an additional question, how audiences think of these 19th century reconstructions as authentic and historically accurate and why and what this means for our accepted notions of authenticity and accuracy. Perhaps it is not necessary here to make any comment on what is considered an audience. Some audiences desire to ‘view the past accomplishments of dance’ and others are more interested in imagining what a historical performance would look like when adding the benefit of ‘improved diet, health, and training regimes’ of the modern period.

As noted by Julian @dodd20 in his *Being True to Works of Music*, it is possible that the distinction here then, is one between 'compliance' authenticity and ‘interpretive’ authenticity. For instance, it is not clear whether Professor Van Camp follows Andrew @kani24 in equating ‘authenticity’ with ‘genuineness’ so that an 'authentic' performance is a mere 'genuine' interpretation of a score, and more importantly what this has to do with the compliance and interpretation distinction. However, one plausible direction in which this discussion could move, is through a focus on interpretive authenticity.

The biggest complication here is that taking the understanding of producing a 'genuine' work means producing an 'authorized' score for that work. But this is not all that determines the authenticity of a work. There are many considerations that go into producing an 'authorized' score. @luka77 would argue that these considerations include the underlying values the score seeks to express. Professor Van Camp considers Swan Lake, The Sleeping Beauty, and Giselle since there are instances of these works that were created without a choreographic notional system. The inclusion of the notational system in order to be authorized then, needs to account of fidelity to some expressed value. Therefore, this fact will have us question the conditions for understanding a work rely solely on the *musical* notation ascribed to a ballet performance and not specific features of the dance itself. Therefore there are at least two different standards for a work's authenticity.

The authenticity of a musical work is often thought to be determined by its compliance with a musical score [@kani24]. This could lead us to primarily only consider just one aspect of its notational score, but it leaves many possible interpretations of its other features, such as those determined by rehearsal notes, drawings, published criticisms etc. Since in ballet we have the remaining constant of musical score, it is plausible that we can solely determine the work's authenticity through an assessment of its compliance with only its musical score or notation. This would work for those reconstructions of nineteenth-century works where we only have the music score and so the musical notation is sufficient for establishing the authenticity of the performance.

If this is the case, then it is not necessary that the authenticity of a ballet performance also relies solely on compliance with its musical score however. Traditionally this has meant that the choreography and other features such as costumes, dancers, etc., is amenable to change without affecting our assessment of the authenticity of the performance. Professor Van Camp asks whether there are other factors in ballet reconstructions and reenactments that could help us to determine whether a given dance is authentic, besides just the musical notation, if any. There are two possibilities here. On the one hand, it is possible that a ballet reconstruction has different critieria for determining authenticity than do reenactments.

One possibility is requiring the same sets of standards that would be employed when considering a historical item for display in a museum. However, reconstructions do not seem to share this aim. For instance, one helpful heuristic of the contrast between reenactment and reconstruction, is to focus on demonstrating how a dance might be redone, or by attempting a phenomenological way of understanding "what it was *like to do it*" [@fran17, 1]. One helpful label of making such a determination then would be to focus on the authenticity of a given performance as either being compliant with a performance's music score, dance score, or some other feature of the performance, or compliance with the original meaning of the work. Yet, here it will be important to define what is meant by "original meaning". Either way, if this is what Professor Van Camp is suggestings, then it seems to me that the narrative of the performance is central to its authenticity.

So while it is not clear what the standards are for a work being authentic, * Professor Van Camp may accept the ballet reconstruction as authentic simply if it complies with the musical score. But using the 1913 performance of *Le Sacre du Printemps* in Paris staged by Nijinsky and the 2009 version staged by Elo, another important question emerges. Here, maybe there are underlying values which a work intends to portray and we can either expect riots when a performance fails to express them adequately, or acclaim when they succeed. With ballet, which can contain both musical and choreographic scores, it would seem that there are additional factors one may consider when attempting to determine authenticity besides fidelity to a performances musical, or dance score. So even if we only consider the musical score for a historic ballet performance, there are still multiple types of authenticity we can rely on and it is difficult to determine a notational score for narrative meaning.



