@magn23 give such an account by highlighting the criminal prosecutions that cite song lyrics as testimonial confessions. Malone argues that being too generous in treating artistic assertions as truth in songs, commits the harm of art-interpretive injustice. She argues that the listener, in this case the prosecution, extends the wrong degree of credibility to the artist. Instead of interpreting the song lyrics as art, the listener interprets the lyrics as testimony.

Importantly, a component of Malone's argument is that prosecutions do not treat other genres of music based on the content of their art. However, there is another and more important issue at concern here. This worry is found in the dual character account of art Malone has previously defended. There, Malone argues that *authentic* country music is a dual character art-form that embodies "the core value commitments of the genre" [@malo23, 1]. According to this view, country music, like punk rock and hip-hop [@liao20] constitute core value commitments. As such, following the dual character account of art, it is not clear what level of credibility we should assign to the song lyrics in criminal prosecutions.

Consider the following dialogue used by @liao20, 7-8:

#### The Scientist

> Alfie: She is not a scientist. I know many people think she is a  scientist, but when you think about what scientists really  are, you will realize that she is not a scientist at all.

> Betty: Of course she is a scientist. She is skilled at running experiments and publishing in scientific journals.

> Alfie: That is not what I meant! What I meant is that she does not possess a genuine willingness to revise her beliefs in light of empirical evidence.

#### The Christian

> Alfie: She is not a Christian. I know many people think she is a  Christian, but when you think about what it really means to be a Christian, you will realize that she is not a Christian at all.

> Betty: Of course she is a Christian. She goes to church every week and believes that Jesus is the son of God.

> Alfie: That is not what I meant! What I meant is that she does not show genuine compassion.

Malone follows @liao20 who argue that we can "pick out the concepts" for which people make various judgments as those above, by distinguishing them from the kinds of judgments "from concepts for which people would not make such judgments" [@liao20, 6]. Here, many things will both satisfy and at the same time fail to satisfy the criteria that allows one to make identity judgments. I argue that here, as a character attribution, these concepts enable one to judge whether someone *truly* belongs to a given category.
