### Elements of emotion

Thought $\rightarrow$ Physiological Change $\rightarrow$ Action Tendency $\rightarrow$ Modulations of Mental Processes

Which is the emotion? More importantly, if you took away one part, would the emotion remain?

### Theories of Emotion

#### From Parts to Theories

##### Feeling Theories

* Feeling Theory: emotions are simply feelings
  * Emotions come from the body
  * We then have an emotional experience
* James-Lange: bodily changes precede our emotional experiences
* Somatic Theory: ( emotions are feelings $\land$ emotional feelings are feelings of bodily changes ) $\rightarrow$ emotions are feelings of bodily state changes
* Damasio, 3 distinctions from somatic:
  1. expanded states: emotional experiences are experiences of changes in the body, but bodily states are expanded
  2. As-If Loop: (interenal milieu, emotions can register changes of levels of chemicals in the brain, brain can enter kind of state it would be in if various bodily changes had taken place).
  3. emotions are not exhausted by feelings.

##### Behavioral Theories

* Behavioral Theory 1: Gilbert Ryle (1949, chap 4)
  * emotions are depositions to behave in particular ways.
* Behavioral Theory 2: B.F. Skinner
  * Names of emotions serve to to classify behaviors
  * Circumstances affect probabilities
* Behavioral Theory 3: J.B. Watson
  * Innate behavioral dispositions associated with certain emotions.
  * E.g., a baby's cries and coos are responses to reinforcing stimuli such as constraint and being stroked.
  * Therefore, emotions are behavioral responses to rewards and punishments.
* Behavioral Theory 4: Rolls 1999
  * Emotions are internal states
  * Still responses to stimuli like rewards and punishments

##### Internal systems of categorization studies

* Easier to recall events when in emotional states that are congruent with those events we are recalling (Bower 1981)
* Positive emotions tend to promote the use of stereotypes (Bless, Schwarz, & Kemmelmeier, 1996)
* Positive emotions help us to reason in ways that are open-minded, optimistic, and creative. Easier time problem solving novel applications of familiar materials (Isen, Daubman, & Nowicki, 1987)
* Negative emotions promote more narrow attentional focus. Anxiety makes us attend to threatening objects (MacLeod & Mathews, 1991; Ohman, Flykt, & Esteves, 2001)
* Depressive Realism: Sadness makes us more pessimistic and sensitive to our flaws (Alloy & Abrahamson, 1988)
* Processing Mode Theory: Some researchers have concluded that emotions can be identified with changes in faculties of attention, memory, and reasoning (E.g., Oatley, and Johnson Laird 1987).

#### Hybrid Theories

#### Dimonsional Appraisal Theories

### From Parts to Plenty

#### The Problem of Plenty

#### Coming Attractions



What are emotions?

Perceptions of patterned changes in the body.

## What is their significance?

* Contribute to reasoning, action, and the election of ends.
* Triggered by judgments and amenable to cultural influence.
* Central to our comprehension of morality.

## But how do they play the above roles?
