Altshuler responds to the reductionistic identity problem by expanding Korsgaard's analysis. On his account then, we are defined by the stories we accept about ourselves, which is determined by our reflexive rather than reflective endorsements. This reflexive endorsement is determined by emotions we express upon our reflection on our narratives. Since on Altshuler's account it is possible for the agent to give an accounting for all of the experiences she has by the way of reflexive endorsement or rejection, this account does not disregard important agent forming experiences. Therefore, his account is grounded in a more comprehensive description of how the agent goes about selecting events that self-prescribe their identity.

The locus of the reduction is hard to pin down in the context of the kinds of desires expressed by an entity as complex as a human person. An analogous complexity can be found in many popular love songs. Although a murky concept, narratives offer a promising way to better understand causal and psychological reductionism. This is because they can incorporate and give shape to "a wide range of heterogeneous" mental states and events [@alts21]. By giving shape to these factors, narrative theories explicate an agent's motivations as a response to environmental effects.

### Narrative production in context

It is important to point out that comparing narrative identity accounts and popular narratives conflates two different understandings of 'narrative'. We might think that *narratives* are insufficient for the kinds of narrative portrayed by Altshuler and Korsgaard. Such narratives then are not controlling in the way Laybourn argues that they are.

Although narrative offers promise, it is also not clear how we might recognize a narrative in the wild, what does a sample narrative look like? Focusing on the expressions of regret in some popular songs may provide one answer. If some songs are narratives, the expressions of regret in them may provide a response to psychological and causal reductionism. As we saw earlier, love songs or anti-love songs can express regret for when the relationship ends, or regret for the relationship not ending sooner; which is another way for thinking about how the narrator's life may have gone differently.

What is important about the expression of the feeling of regret here, is what that experience does for the agent's behavior going forward in the context of the meaning that the narrative gives to that event, or the agent derives from it. Love songs could be a form of narrative thinking in both the philosophical context and the popular one. Importantly here however, love songs might be a process by which someone organizes their experience and creates their own identity [@sche96].

As such, the second kind of question is a question about what we believe to be true about ourselves. Related to this then is a question about what extent do our environments contribute to our beliefs about what is true about ourselves, including our moral and other obligations. Here I suggest then that how we should understand such questions, who we are, is in the form of narrative regrets. How we should understand art then, is as a way of exploring expressions of narrative regret.

Even more important for our context of identity, this narrative thinking is always done in the context of self-other relationships. As such, the emotion of love is important, and regret is important for understanding the importance of love for self-identity. Without this particularly self-other relational thinking rooted in love, it is difficult for the victim to develop an authentic understanding of who she is.
