# Preface

Langer notes a shift in philosophical thought wherein philosophical theories are more accomodating of the empirical sciences. Philosophers are also now applying these new patterns of philosophical thinking to traditional philosophical questions. These patterns of philosophical thinking that are grounded in and made possible by, an advanced use of symbols as reference of more abstract phenomena. This does not make it clear what this shift is however.

* What is the relationship between art and knowledge?
  * Idealism: Expressive forms of human understanding, science, myth, analogy, metaphorical thinking, art, are all grounded in "intellectual activities determined by 'symbolic' modes."
  * Kant: The relationship between art and knowledge is grounded in a "phenomenal character of experience". What this means is that the relationship between art and knowledge is one of experience.
  * As such, art is a symbolic form of conception, meaning that art makes possible new forms of experience.
* The shift then is towards the use of symbols to understand ultimate reality. How is it that we use symbols to understand ultimate reality?
* One reason why we may think that it doesn't is because we might think that art as symbol only explains an idealist conception of reality? What this means is that symbols do not represent actual reality, only idealized reality. This is because what symbols show us, is that there are many aspects of reality that we do not have access to.
  * Urban: Yes, as humanity develops its use of language, using symbols to explain complex phenomena, e.g., in communicating "there is a dangerous animal over there", the proposition serves as a "signal" that allows us to "develop a characteritic attitude toward objects *in abstentia*", 'thinking of' or about, 'referring to', "what is not here." [31]
