# Working Papers 2026 – Status Dashboard

Current status as of `r format(Sys.Date(), '%B %Y')`

## Active Papers

::: {.callout-important appearance="minimal"}

### Manticore

- [ ] Literature Review
- [ ] Primary texts read & noted
- [ ] Brainstorm Core Argument
- [ ] Draft paper outline with main sections
- [ ] Write first draft
- [ ] Share draft with trusted colleagues
- [ ] Identify possible objections
- [ ] Research Relevant Conferences
- [ ] Research target journals for submission
- [ ] Objections section started
- [ ] Responses to objections
- [ ] Submit to journal X by end of Q2

:::

::: {.callout-tip appearance="minimal"}

### The Aesthetic Problem of Evil

- [ ] Literature Review
- [ ] Primary texts read & noted
- [ ] Brainstorm Core Argument
- [ ] Draft paper outline with main sections
- [ ] Write first draft
- [ ] Share draft with trusted colleagues
- [ ] Identify possible objections
- [ ] Research Relevant Conferences
- [ ] Research target journals for submission
- [ ] Objections section started
- [ ] Responses to objections
- [ ] Submit to journal X by end of Q2

### Morality as Privilege

- [ ] Literature Review
- [ ] Primary texts read & noted
- [ ] Brainstorm Core Argument
- [ ] Draft paper outline with main sections
- [ ] Write first draft
- [ ] Share draft with trusted colleagues
- [ ] Identify possible objections
- [ ] Research Relevant Conferences
- [ ] Research target journals for submission
- [ ] Objections section started
- [ ] Responses to objections
- [ ] Submit to journal X by end of Q2

### God as the Best Possible Epistemic Ground of Human Dignity

- [ ] Literature Review
  - [ ] Imago Dei as Human Identity by Ryan Peterson
- [ ] Primary texts read & noted
- [ ] Brainstorm Core Argument
- [ ] Draft paper outline with main sections
- [ ] Write first draft
- [ ] Share draft with trusted colleagues
- [ ] Identify possible objections
- [ ] Research Relevant Conferences
- [ ] Research target journals for submission
- [ ] Objections section started
- [ ] Responses to objections
- [ ] Submit to journal X by end of Q2

:::

## Next Up

- [Aesthetics of Evil](./papers/paper-1-aes-evi/index.qmd)
