### The Manticore

The Manticore is a fictionalized beast that was born in Persian art and literature sometime around its cultural zenith. It at once symbolizes evil, death and hell, but in medieval religious art, it came to symbolize the power of Christ over death and hell.

On some accounts, the manticore is a union between a hyena and Ethiopian lioness. It imitates the voices of men and possesses a fixed and immoveable gaze. In addition, it does not possess gums in either of its jaws, and rather than having multiple teeth, it has one large one.

Ctesias argued that the Manticore had a triple row of teeth which fit into each other like a comb, the face and ears of a human, blood colored eyes, the body of a lion and a stinging tail similar to a scorpion. While Pliny the elder argued that it imitated the voices of men, Ctesias tells us that its voice resembles a union of a flute and trumpet, that it is exceedingly swift, and has an appetite for human flesh [p. 280].

Aristotle questions Ctesias' account, but nevertheless records it in his writings. He gives Ctesias' account, that the Manticore possesses a double row of teeth, similar feet and size of a lion, with ears and face like a man. Grey colored eyes and a red body, with a tail like that of a scorpion. [p. 30-31; also see Aristotle, History of Animals 8.28, 605b22-606a10]

Owing to the fantastical nature of these accounts, it is highly probable that they are either misguided or motivated by some purposes other than truth. In the 57th question of the 1st of the second part of the Summa Theologica, Thomas Aquinas defends the view of art as a form of right reason. There is a distinction here between the right reason for making objects, and the right reason for doing good actions. We should first focus on the point that is important to both of these activities, is the right use of one’s cognitive faculties. The difference lies in the produced object, whether an action or thing.

If we are to ask ourselves what justifies our emotional responses to some given experience, on the one hand we might consider that the validity of the experience rests in something like the authenticity of the experience. Assuming that artistic experiences are driven by the same norms as other experiences, the image of the Manticore would generate fear in those who were lucky enough to witness an artistic representation of one, whether literary or visual. However, artistic experiences are not always governed by the same norms as other kinds of experiences. Some additional norms that govern our experiences with fiction include pleasure, entertainment, and absorption [@gilm20, 132]. However, this would mark an important divergence from the functions of art accepted by the medievalist, and those accepted by us today.

Considering a product that is produced, the desired outcome of the activity of art, it is not clear what it is exactly, that we care about in the case of art. When it comes to what is produced in the case of art, it is not clear whether the final thing produced is an action, or a material commodity. The common contemporary understanding considers various perspectives. However, it is important to understand two important points here.

Why do we think that fairy tales are fiction but news stories are not? Is fake news the same thing as a fairy tale? During the pandemic, fake news became a widely discussed talking point. A less widely discussed talking point however was why don’t we just call it fiction? A derivative of this question is how fiction is made possible. Meaning, what are the creative differences between fake news, news news and fairy tales? To answer this question, Gregory Currie suggests three possible answers.
According to the front page news, the terrorist leader Amelia Boyd was killed by the Headhunters Gang. First are the characteristics that distinguish fiction from non-fiction. This question is a close investigation of the entities that are in fiction and make them possible. For instance, the psychological and linguistic resources that producers and consumers of fiction must have access to.
