---
title: "Unjust Religion as Fiction"
---

Susan Pepper-Gates writes a very engaging and important paper criticizing article applying Miranda @fric07's analysis of epistemic injustice to contemporary Western Religion WR, and the Philosophy of Religion, PoWR. She argues that the philosophy of religion should cultivate epistemic-ethical virtues in order to recognize and include philosopers from minority voices. Doing so helps WR and PoWR understand and recognize the ways that power shapes our lives as embodied social beings.

I think that the initial conclusion is a strong one. Namely the ways that power shapes our lives as embodied social beings. However, I think that the most important conclusion here is a premise conclusion statement, rather than just a conclusion. Rather than WR and PoWR cultivating epistemic virtues, WR and PoWR should focus on the cultivation of epistemic virtues. This will give the project of WR and PoWR two convergent aims.

1. First, it would be to draw attention to the ways in which power ***can*** shape our lives as embodied social beings.
2. Cultivating virtue in this context then, means that WR and PoWR ought be formative, cultivating virtue in their audiences.
3. This virtue in turn makes it less likely that power will shape the lives of members of WR and PoWR's audiences.

Finally, though I will not have space to argue this here, I would add that versions of WR and PoWR has already historically done this.

## Some Questions

I have some initial questions which I will articulate first here:

What harms are suffered by which groups? This point is probably more appropriate to ask of the broad literature and I am not sure that it has not been raised yet. However, if it has, then it seems that it would be an important point to include here. Following are a couple of reasons why I think this is true.

1. As I can tell, it is hard to understand why a racial or gendered minority may believe that a white samesex male couple ought to be considered marginalized in any context.
2. E.g., we might think that a white heterosexual couple should be considered more marginzalized than the white male samesex couple.
   1. White men have more social mobility than white women.
   2. Therefore, two white men have more social mobility than one white man and one white woman while one white man and one white woman have more social mobility than two white women.
3. On the other hand, we might have reason to suspect that a white female samesex couple is considered more marginalized than the white heterosexual couple.

The second question is one of difference in kinds of harm. Is the kind of harm faced by racial, or ethnic minorities different from the kind faced by sexual preference? What about the kinds of harms faced by immigrant groups verses those faced by native born populations?

## Peppers-Gates Analysis of Fricker

1. Western Religion, WR, and The Philosophy of Western Religion, PoWR, ignore work by intersectional feminist philosophers and philosophers of race who challenge the traditional approach,
   1. Traditional epistmology, TE, focuses on abstract universal knowledge.
   2. Philosophy of religion grounds itself in TE and focuses on rational belief

The philosophy of religion should cultivate epistemic-ethical virtues in order to recognize and include philosopers from minority voices.

Some initial confusions:

1. What harms are suffered by which groups?
   1. A white samesex male couple may not be considered marginalized in any context. E.g., white heterosexual couple should be considered more marginzalized than the white male samesex couple while the white female samesex couple is considered more marginalized than the white heterosexual couple.
   2. White men have more social mobility than white women. Two white men have more social mobility than one white man. Therefore, two white men have more social mobility than one white man and one white woman while one white man and one white woman have more social mobility than two white women.
2. The kind of harm faced by racial, or ethnic minorities is different from the kind faced by sexual preference.

1. WR and PoWR ignore work by intersectional feminist philosophers and philosophers of race who challenge the traditional approach,
   1. Traditional epistmology focuses on abstract universal knowledge.
   2. Philosophy of religion grounds itself in traditional epistemology and focuses on rational belief
2. Therefore WR and PoWR embrace narrow methodologies that exclude others and contributes to the marginalization of minority voices.
3. Therefore WR and PoWR conflate the truth about the existence and attributes of a [pateriachal] God with traditional epistemic approaches grounded in [narrow methological approaches to knowledge].
4. By focusing on narrow methologies and abstract conceptions of knowledge, WR and PoWR fail to consider ways that power shapes our lives as embodied social beings.

WR and PoWR have silenced marginalized groups. These inclde women, people of color, disabled persons and LGBTQI community members [if these voices are marginalized, how can they be considered community members?].

This is because traditional epistemology, TE, focues on abstract conceptions of knowledge and thereby fails to consider the ways that power shapes our lives as embodied social beings [Using the grammar contrast, we assume that a person can learn grammar and we exclude them from the larger conversation until they do. Do we not think that a person can learn how to operate within the rules invoked under 'abstract conceptions of knowledge'?].

TE focues on abstract conceptions of knowledge and thereby fails to consider the ways that power shapes our lives as embodied social beings [Using the grammar contrast, we assume that a person can learn grammar and we exclude them from the larger conversation until they do. Do we not think that a person can learn how to operate within the rules invoked under 'abstract conceptions of knowledge'?].

1. WR and PoWR ahve silenced marginal groups [calling groups marginal seems to marginalize them].
   1. TE focuses on abstract conceptions of knowledge and therefore fails to consider ways power shapes our lives as social beings.
   2. PoR grounds itself in TE by focusing on 'rational' belief in its debates about God's existence and attributes.
   3. Therefore PoR ignores feminist philosophers and philosophers of race who challenge PoR grounds in TE (fp and por then reject 'rational' belief?).
2. PoR's embrace of its narrow methology and range of topics then is based in an exclusion of 'others' from meaning making in institutional philosophy.

My contribution: The Philosophy of religion focuses on rational belief and conflates this in its debates about existence and attributes of a pateriachal God.

## Silencing

Western religion and philosophy of religion have silenced marginalizxed groups by focusing on abstract conceptions of knowledge which fails to consider ways that power shapes our lives as emboidied social beings.

1. Traditional epistemology focuses on abstract conceptions of knowledge.
2. These are inadequate because they do not analyze the ways power shapes our lives as "embodied social beings".
   1. We are born in webs of meaning and social relations of [power and prvilege (are journal review practices an exercise of power and privilege?)].
   2. Some voices are heard [pass review], meaning that they shape the social imagination (define social imagination) and others are ignored [do not pass review and therefore . . .]. They are incapable of shaping the social imagination.
      1. However, how is this done? One way is through the enforcement of so-called grammar rules. Taking an art class, the attempted to communicate the rules which apply to a given art genre. However, the students noted the many deviations from these rules. The teacher replied by saying that "once you know how to apply the rules, then you are allowed to break the rules".
      2. An imagined analogy would be a reviewer rejecting a paper for the alleged abuse of grammar rules, syntax, and not content, truth value, where the so-called rules are applied as a means of gatekeeping who gets to shape the 'social-imagination'. A student who fails to learn the rules, is not accepted into the art community, there work is posted in galleries, sold at auctions, is not publically (positive or negative) reviewed.
   3. This excludes people from shared social understanding, contributing to the harm of that individual, can be used as a weapon that harms.
      1. What is this weapon and how specifically does it harm?
        1. Participation in shared conceptual structure is a marker of humanity.
        2. Therefore gatekeepers undermine the process by which a person becomes human.
           1. Better, is to say they undermine the process by which a person is considered human.

## Hermeneutic Injustice

1. When DSS (Dominant Social Structure) of meaning exclude you or distort your experiences, and no social concepts that you recognize capture your vision of yourself, then your capacity as a knower and your own self-understanding have been stunted.
   1. But this introduces a very narrow vision of social structure. Isn't it possible that while you are excluded from a dss, a non-dss, one that includes you and does not distort your experiences, could still capture a vision of yourself, and your capacity as a knower and fortifying your self-understanding.
   2. What is needed then is a new non-dss, education.
   2. While a person is excluded from a dss, they could have their capacity as a knower fortified by a non-dss, education reimagined.

The need to reimagine eduction.

1. WR and PoR become DSS's of meaning and exclude some or distort their experiences
2. But this introduces a very narrow vision of social structure.
   1. It is possible that while you are excluded from a dss, a non-dss, one that includes you and does not distort your experiences, could still capture a vision of yourself, and your capacity as a knower and fortifying your self-understanding.
   2. So while a person is excluded from a dss, they could have their capacity as a knower fortified by a non-dss.
3. Therefore 2 this does not mean that there are no social concepts that you recognize and capture your vision of yourself and your capacity as a knower and your own self-understanding are stunted but not by the DSS, but the lack of the non-dss.

### One Possible example of hermeneutic injustice against religious minorities

Secular community marginalization against people of religious faith.

1. PoRF may lack 'sensibilities and resources needed to make sense of religious people's experiences," (Kidd, 20217).
2. But does not capture gravity of systemic cases of hermeneutical injsutice whose targests experience multiple forms of injustice.
   1. Hermeneutical marginalization "entails mariginalization of a socioeconomic sort', targets will not 'participate on equal terms within the practices of law, academia, politics, religion, journalism, media, etc. (Fricker, 2010).
      1. However, DSS vs. non-DSS? While DSS of meaning may distort experiences, non-dss may not, instead rejecting dss of meaning which says that "there are no social concepts which capture a religious person's vision of themselves (i.e., made in image of God, human dignity bestowed by God, not DSS, etc.)". Consider the following claims:
         1. Here, Fricker, a published philosopher, the DSS, says persons of a certain sort are marginalized and therefore have been silenced. But here, marginalization means they lack a marker of humanity. As such, Fricker claims that certain individuals lack a marker of humanity.
            1. Why? For not adhering to rules of rationality practiced by the dss. Surely they could however do so?
            2. Because of 1, they lack participation in shared meaning.
            3. Therefore lack capacity as knowers.
            4. From 3, their self-understanding is mitigated and stunted.
            5. Participation in shared hermeneutic, i.e., 1-4, in shared conceptual structure is a marker of humanity",
            6. Therefore, because of exclusion from shared conceptual structure, they lack a marker of humanity.


but rather than 'victims' being excluded from shared conceptual structure and lacking capacity as knowers and lacking marker of humanity, they instead are included in different conceptual structure (e.g., religious conceptual structure) which fortifies their capacity as knowers and self-understanding, acting as marker of humanity.
