# Presence in Pedagogy: At the Heart of Learning Philosophy

The perceptual illusion of nonmediation:

* Communication, psychology is an attempt to understand how we understand and interpret information in nonmediated settings, store and retrieve information, memories, make decisions. (3)

1. Presence as social richness: "presence is the extent to which a medium is perceived as sociable, warm, sensitive, personal, or intimate when it is used to interact with other people. (Short, Williams, and Christie, 1976)" , (5).
2. Presence as realism: "presence is the degree to which a medium can produce seemingly accurate representations of objects, events, and people---representations that look, sound, and/or feel like the 'real' thing" (6).
3. Presence as transportation: "user is transported to another place".
4. Presence as immersion: "the degree to which the virtual environment submerges the perceptual system of the user" (Biocca & Delaney, 1995, p. 57).
5. Presence as social actor within medium: user's responses "to social cues presented by persons they encounter within a medium even though it is illogical and even inappropriate to do so". [See Lombard, 1995 and Lemish, 1982]
6. Presence as medium as social actor: "social responses of media users to cues provided by the medium itself [13].

But what is the distinction of presence in mediated and nonmediated environments? Arguably, if the illusion is not an illusion, but fact about the environment, then we would say that the person is present.

> An "illlusion of nonmediation" occus when a person fails to perceive or acknowledge the existence of a medium in his/her communication environment and responds as he/she would if the medium were not there. [13]

Nonmediated: experienced without human-made technology

Nonmediated presence, experience w/o human-made tech
Mediated presence, experience *as though* w/o human-made tech
