---
title: "Narrative Regrets in Truth and Fiction"
subtitle: "God as the Best Possible Epistemic Ground of Human Dignity"
abstract: "Following @gold09's short paper *Narrative Thinking, Emotion, and Planning*, I consider the representation of emotional expressions of regret, *narrative regret*. I draw specific attention to the context of the representation of distinct special relationships in fiction. Important here are discourses on the fictional representation of such relationships as a special kind of human agency. I argue that a related concern are the assumptions about what is true and what is fiction in popular fiction, where what is true are expressions of relational sanctification that is grounded in a divine union of love appropriate to friendship."
author: |
  Montaque Reynolds
  Philosophy Department
  Saint Louis University
  Saint Louis, MO. 63110
  montaque.reynolds@slu.edu
bibliography:
  - ./../../Un-Duplicates.bib
format:
  pdf:
    linestretch: 2
    include-in-header:
      - ./preamble.tex
---

# Introduction

Wendy @layb18 draws a comparison between black authenticity and what she calls commodified realness. According to Laybourn, identity is sold to a broader public as black authenticity. This criticism is centered around the effects of what she calls *controlling images* in popular media. Of deep concern here, is that many of the members of the communities depicted by such images, consider aspects of these images to be authentic representations of themselves and the communities in which they live. Therefore, there is a public perception that such images are not in themselves harmful. If they are in some degree controlling, then they would be harmful, but there is strong disagreement regarding whether or not they are [@20c14; @coll06; @coll09; @sart98b].

I consider the hermeneutic implications of this puzzle. It is not clear just specifically which aspects of the member's lives are being represented. It is also not clear which images are harmful considering that such images are accepted as representative [See @smit97; @shus07; @lind13]. @coll06; and @coll09 has placed much emphasis on this later point. Unfortunately, this specific interpretation of her work has not achieved the recognition in the epistemology literature that it deserves.

First, taking Miranda @fric07's work on epistemic injustice, there is a conceptual space to understand the affects of the kinds of controlling images articulated by Collins. The primary accounts of epistemic justice focus on testimonial, whether or not a person's testimony is accepted, and hermeneutic injustices, whether or not knowledge is attributed to the victim. Unlike general accounts of knowledge however, moral knowledge has often been understood as a special kind of second-person perception [@arpa04a; @hill09; @nuss90f; @nuss01; @flet16b; @howa18b; @sliw17a among others].

On the one hand then, a form of epistemic injustice occurs when the wrong values are attributed to a victim because of they fail to accept the testimony of the victim. On the other hand, a form of epistemic injustice occurs when the audience is prevented from understanding the victim because the victim is incomprehensible to the audience, while the audience does listen to the testimony of the victim, the victim is unable to communicate their meaning. It may be the case, for instance, that the victim is attempting to communicate certain value concepts to the audience. But the audience is unable to attribute these concepts to anything the victim would intend to communicate. Therefore, if Collins is correct, a person becomes a victim when members of a community fail to attribute value concepts to a victim on account of some irrelevant non-communicative feature. An example of this practice is the belief that nuclear households are a "structural mechanism of White hetero-patriarchal family supremacy" [@leti24] rather than a potentially universally shared value devoid of racial connotations. On this account, denying the existence of non-white nuclear households would be committing acts of epistemic injustice to non-whites who choose to advocate for nuclear families.

But if we consider moral knowledge accounts, testimony is grounded in emotional expressions of reactive attitudes. Here, we derive a particular understanding of a person's accepted values from the way he or she responds to a particular state of affairs. Such accounts characterize moral knowledge, specifically, as a kind of feeling, or an apt emotional response to an event or action [@harr11]. This harm occurs when we fail to attribute a particular emotional experience to someone on account of some non-relevant / non-personal feature of who they are. An example would be denying that someone experiences heartbreak on the dissolution of his or her relationship. Therefore, it is to deny a given phenomenal experience to an individual on account of the non-relevant feature. As such, this specific epistemic harm is two fold. Not only are others prevented from (morally) understanding the victim, the victim is potentially prevented from (morally) understanding herself, she is unable to truly understand what her values are. In other words, she and others are prevented from truly understanding the victim.

Although it would be important to carve out specifically just in which ways the epistemology literature misses these points, I think that it will be more fruitful to provide a way to mitigate these harms. An important question here has to do with the relationship between popular narratives that contain these images, and personal identity. One approach, *narrative identity\* *, argues that we are defined by the stories we accept about ourselves. Therefore at the center of the response, is an account of how victims can choose their own stories.

Important here are narratives as the representation of humanity in artifacts of culture. Some similar examples of this criticism can be found in @mbem17's *Critique of Black Reason* or Zakiyyah Iman @jack20. @jack20, for instance, uses the view of race as a social construct. According to this view, 'black' represents a void of reason and a surplus of animality. It is not clear what the counter to this claim should be as it is not represented anywhere in either work. After highlighting some examples regarding the expression of regret in popular media, I provide a summary of the literature on narrative identity. I suggest that narrative identity' is a better alternative. I then propose what I call narrative regret as a necessary component of 'narrative identity\*'.

I compare three songs as quintessential examples of narrative regret; *By yourself* by Ty Dolla \$ign, a song about financial and relational independence and *Rich and Sad* by Post Malone, and *Insecure No More* by Alex Jean. The protagonist in *by yourself* is praised for her ability to sever her relational ties without regret from a partner who is unwilling or unable to financially contribute to that relationship. In contrast, the song *Rich and Sad* by Post Malone is a song about relational dependence where the protagonist expresses his regret at pursuing wealth and other material possessions rather than a special relationship. In contrast to the two, Jean in *Insecure* uses regret to express ways in which he reclaims his human agency. As examples of narrative regret, I consider whether one is more expressive of human agency than the other.

# Robust vs. Generic Expressions of Regret

What is the difference between harm done in regard to someone's capacity as a knower and their capacity as a 'moral' knower? Related to the victim's capacity as a moral knower, is the victim's capacity *as a person*, where personhood denotes more specifically, their own moral agency, held values, and the like. Patricia Collin's work is central to contemporary literature on standpoint epistemology precisely because of the possible implications for self-knowledge and moral agency [See @coll06; and @coll09]. Of little notice however, are her contributions to questions about authenticity and representation and where these intersect with moral agency.

Discussions following Miranda Fricker's work are centered around the moral wrongs of epistemic injustice. These are defined as wrongs of testimonial inference where the victim is wronged in their capacity as an epistemic knower [Especially see @fric07, 44]. The victim's credibility as an epistemic agent is diminished and as such, she is made unintelligible to a broader public. However, the wrongs do not draw enough attention to a specific kind of moral harm. Here, 'moral' implies 'moral' information, or 'moral' knowledge and self-knowledge or understanding.

Fricker hints at the moral non-moral implication by drawing attention to cases where an agent's epistemic contributions are diminished when she notes that "the epistemic wrong bears a social *meaning* to the effect that the subject is less than fully human" [@fric07, 44]. While Fricker emphasizes the word 'meaning', I would argue that proper emphasis should be added to the word *social*, drawing instead to the word *'social meaning'* as the proper focus of the epistemic wrong.

## Art Interpretive Justice

Emma @magn23a gives such an account by highlighting the criminal prosecutions that cite song lyrics as testimonial confessions. Malone argues that being too generous in treating artistic assertions as truth in songs, commits the harm of art-interpretive injustice. She argues that the listener, in this case the prosecution, extends the wrong degree of credibility to the artist. Instead of interpreting the song lyrics as art, the listener interprets the lyrics as testimony.

Importantly, a component of Malone's argument is that prosecutions do not treat other genres of music based on the content of their art. However, there is another and more important issue at concern here. This worry is found in the dual character account of art Malone has previously defended. There, Malone argues that *authentic* country music is a dual character art-form that embodies "the core value commitments of the genre" [@malo18, 1]. According to this view, country music, like punk rock and hip-hop [@liao20] constitute core value commitments. As such, following the dual character account of art, it is not clear what level of credibility we should assign to the song lyrics in criminal prosecutions.

Consider the following dialogue used by @liao20, 7-8:

#### The Scientist

> Alfie: She is not a scientist. I know many people think she is a  scientist, but when you think about what scientists really  are, you will realize that she is not a scientist at all.

> Betty: Of course she is a scientist. She is skilled at running experiments and publishing in scientific journals.

> Alfie: That is not what I meant! What I meant is that she does not possess a genuine willingness to revise her beliefs in light of empirical evidence.

#### The Christian

> Alfie: She is not a Christian. I know many people think she is a  Christian, but when you think about what it really means to be a Christian, you will realize that she is not a Christian at all.

> Betty: Of course she is a Christian. She goes to church every week and believes that Jesus is the son of God.

> Alfie: That is not what I meant! What I meant is that she does not show genuine compassion.

According to Liao *et al*, we can "pick out the concepts" for which people make various judgments as those above, by distinguishing them from the kinds of judgments for which people would not make similar judgments. Here, many things will both satisfy and at the same time fail to satisfy criteria allowing one to make identity judgments such as 'christian' or 'scientist'. These enable one to judge whether someone *truly* belongs to a given category.

Malone follows @liao20 who argue that we can "pick out the concepts" for which people make various judgments as those above, by distinguishing them from the kinds of judgments "from concepts for which people would not make such judgments" [@liao20, 6]. Here, many things will both satisfy and at the same time fail to satisfy the criteria that allows one to make identity judgments. I argue that here, as a character attribution, these concepts enable one to judge whether someone *truly* belongs to a given category.

## Testimonial and Hermeneutical Injustice

Art injustice is treated as a form of testimonial injustice. Listeners "extend the wrong degree of credibility". Then, the testimony of the speaker is called into question because of the identity of the speaker. In people v. medina, Alex Medina was accused of murdering Seth Scarminach. In the case, the prosecution attempted to use song lyrics performed by Medina as an admission of guilt. When Alex Medina was tried for murder, he experienced an art interpretive injustice because "In cases like Medina’s, the rapper is either not deemed to have produced a work of art at all or deemed presumptively to have produced art which is confessional". As such, Medina's lyrics were treated as confessional rather than a work of art. But Medina does not suffer from credibility deficit, hermeneutic injustice, because his lyrics were used as credible evidence. Although Medina was employing artistic license, he was not treated as such.

Hermeneutic injustice, unlike testimonial injustice, occurs "when someone's own experience is obscured because the available concepts distort it or render it inscrutable". Yet, as a counter to Malone, Medina's case can also be one of hermeneutic injustice. Important to this point, is that social experiences are "obscured from collective understanding". This is caused by the structural identity prejudice in the "collective hermeneutic" resource. Important here, is the fact that analogous to the Medina case, it is highly likely that audiences misdescribe the victim's narrative experiences, reinterpreting regret as empowerment [See @fric07; 169].

# Practical Identity (Narrative Identity)

In previous work, @malo23a argues that country music allows its audiences "reconnect with, reify, and revise" a common *practical* identity. There is no reason to think that country music in this regard is any different than rap and hip-hop in that both genres provide opportunities for their audience to make character assessments about the members of a category.

A hermeneutic artistic injustice then is not the failure to attribute art concepts to a person's work because of their identity; "identity prejudice and the matter at issue is the application of shared art concepts" [@magn23a]. This is important in the conversation of black country music. But here, the early epistemic literature above, the injustice occurs when certain concepts common to a genre (love, relationship, family, community) are the cause of the identity prejudice in the "collective hermeneutic" resource. For instance, when values often associated with a given genre are the reason for denying an artist inclusion into that genre. Contemporary discussions argue that an artist is denied because of their race, however, while this may be true, it is important to understand the full implications here.

The failure to include an artist in a genre stems from a failure to attribute shared value concepts that would be inferred by that person's inclusion into a given genre. As such, there are two competing versions of victimhood relevant to Medina's case. On the one hand, Medina's lyrics are treated as art because of a lack of remorse characteristic of the artistic genre he is a part of. On this account, his lyrics are celebrated as art and not expressions of regret or testimony. However, on the other account of harm, instead of treating his lyrics as art, identified by the shared lack of remorse and regret common to the genre, they are instead treated as testimony, i.e., expressions of regret (confession) that we might think are characteristic of a more universally expressed emotion.

The social version of this question is more opaque. It is a question about our social environments and to what extent our social environments can provide us with the resources necessary to fulfill our moral obligations, representative expressions of a universal value, i.e., characteristic expressions of regret when failing a moral obligation. Once again, there are two questions here however, the first asks how our moral obligations define us. More important, i.e., more manageable here, is the second which asks how our experiences of regret entail those obligations or entail our acceptance of these obligations.

## Identity Reductionism

Here I focus on a narrowly defined understanding of intra and extra personal character assessments. Narrative accounts of identity attempt to use the way an individual responds to events in a person's life to identify the agent through space and time. For instance, in the agency literature, reductionists explain the metaphysical continuity of an object across space and time in terms of personal identity. Derek @parf87 argues that in order to understand what sort of object a person is, we need to understand two different qualities. These include the nature of a person and their *criterion of identity*, i.e., their continued existence over time. But when we consider these qualities in contrast to persons versus non-persons, we include not only physical states of matter, but also immaterial ones such as mental states, memories, beliefs, motivations, etc. A person can be identified just if continuity between subsequent immaterial mental states and physical states are achieved.

Reductionists such as Parfit can define personal identity as the persistence of the human person over time, and say that this is reducible to the binding of psychological states with physical matter. Causalism is the most popular account that explains the origin of psychological states, an object *A* at time *T$_1$* is identical to object *B* at time *T$_2$* as long as we can draw a continuous line from object *A* at time *T$_1$* to object *B* at time *T$_2$*. The continuous line here is most often mental states such as memory, passions, character traits and dispositions. But often times it is the case that those memories we accept as definitive, have their origins in persons or events other than ourselves. There are certain dispositions I have because of persons other than myself signing various documents articulating what rights I recognize as belonging to me for instance.

While Parfit's account does show how persons are not mere matter, he and other causalists state that an action performed by an agent, is an event caused by the mental state of that agent [@alts21]. The difficulty arises in understanding how mental states are related to prior events. While a mental state may be the source of some event, another event may be the source of another mental state. Regardless of the relationship between mental states and the material universe, it is not clear where the causal chain originates.

In response, Christine @kors89 has argued that on @parf87's account of identity, a person is primarily a *locus of experience* [@kors89, 103]. This means that the way to identify an object as existing through space and time as it correlates with a person, is by identifying a set of experiences between objects across space and time that are connected through a set of events or some other connecting factor. These events are psychological states and 'spatiotemporally continuous living bod[ies]' [@kors89, 104]. In this way I might define myself as *an American* and defend such values as independence and freedom. It is plausible then to draw a line from events in 1776, America's founding, to my present day. Therefore I associate various values I hold with events that transpired in 1776 and as such, the psychological states I currently have, have their own origins centuries before. In other words, because a person's psychological states have prior causes, the states themselves are merely some form of event and experience.

Narrative accounts then are responses to impersonal accounts. According to narrative accounts, how we frame events such as these, is what makes the event meaningful for a given individual [@sche96b, 96]. Without narratives, the agency and the identity of the subject is lost among a causal chain of events. This has been called 'constitution'. In terms of the constitution model of identity, without the binding effect of narrative, the subject of a given event is victim to a disparate causal chain of cause and effect. Our identity then would merely be an impersonal metaphysical continuation of matter [@kors96].

The meanings that stories provide are not derived from the individual meanings of the events they represent, rather the individual events derive their meaning from the overall meaning of the story. The outcome of the story determines the meaning of the events within the story. Why something happened is explained by the end of the story in which it happened. But this is ascribed by the agent, that individual. The difficulty arises in understanding how mental states are related to events, whether emotional, causal or something else. The divergence not only has implications for ways in which we identify material objects persisting across space and time, but also with respect to moral attributions of praise and blame. These uniquely belong to active *immaterial* objects such as persons.

Kantians and Utilitarians have differing conceptions of agency which together represent a source of justification for either view. When concerning moral obligation and duty for instance, it is the moral agent who deserves to be praised or blamed. In this way, say my acceptance of a person's human rights, has nothing to do with me. Utilitarians on the other hand ask 'what should be done for the agent?', persons with a characteristic form of experience and the Kantian asks 'what ought the agent do?', despite a given experience. Parfit's account does not account for what we all might think of as the exercise of agency. As such, Korsgaard goes on to argue that focusing on what an agent does, rather than their experiences, will lead to a drastically different concept of identity, one that is grounded in a unique characterization of agency. She calls this characterization 'practical' identity.

Korsgaard then, defends a concept of narrative identity. Reductionist and causalist conceptions of identity undermine what we think of as agency with regard to moral responsibility. These accounts fail to explain the attribution of praise or blame in response to an agent's actions. They offer no way to define the line as beginning at *T$_1$* and ending at *T$_2$*. On this account, the object, that persistent thing deserving of either moral praise or blame, is indefinable.

On her narrative account of identity, a person is an agent who uses narrative to define her own constitution. She calls this the *self*-constitution model of personal identity. As such, Korsgaard defends an account of personhood and identity grounded in narrative agency. On this account, we are defined by the stories we accept about ourselves. The act of acceptance means that we select individual events from our pasts in order to construct a narrative that defines us.

As an explanation, narrative theories provide one account of personhood by explaining the relationship of cause and event in a way that preserves agency. Stories make our lives intelligible [@vell03] by providing motive and context to a collection of events and episodes. In other words, narrative gives meaning to otherwise meaningless events. Overall, the meanings that stories provide are not derived from the individual meanings of the events they represent. Rather, the individual events derive their meaning from the overall meaning of the story. The outcome of the story determines the meaning of the events within the story. Finally, the meaning of the outcome is determined by the story teller. Why something happened is explained by the end of the story in which it happened.

The second question is even more difficult and grounds the first. It begins as a question about ourselves and the sources of our beliefs as to what is possible. Peter @gold09 convincingly argues that we would not experience regret for an event that we had no control over the same way we would for an event we did have control over. It will first be helpful to understand how narrative theories shape our identities.

## Constitutionalism reconfigured (Narrative Identity\*)

Altshuler identifies a problem with the above account, namely that it does not account for those events that are not selected by the agent. He argues that such events do have a causal effects on what ultimately constitutes one's identity. Following Peter @gold09, Altshuler instead identifies narrative with an agent's *ability* to reconfigure their motivational and psychological past with respect to their own reactions to these events. In other words, Altshuler too, defends a self-constitution model of agency and identity, but one on which a person's responses to his or her past, shape her future identity.

Altshuler responds to the reductionistic identity problem by expanding Korsgaard's analysis. On his account then, we are defined by the stories we accept about ourselves, which is determined by our reflexive rather than reflective endorsements. This reflexive endorsement is determined by emotions we express upon our reflection on our narratives. Since on Altshuler's account it is possible for the agent to give an accounting for all of the experiences she has by the way of reflexive endorsement or rejection, this account does not disregard important agent forming experiences. Therefore, his account is grounded in a more comprehensive description of how the agent goes about selecting events that self-prescribe their identity.

The locus of the reduction is hard to pin down in the context of the kinds of desires expressed by an entity as complex as a human person. An analogous complexity can be found in many popular love songs. Although a murky concept, narratives offer a promising way to better understand causal and psychological reductionism. This is because they can incorporate and give shape to "a wide range of heterogeneous" mental states and events [@alts21]. By giving shape to these factors, narrative theories explicate an agent's motivations as a response to environmental effects.

### Narrative production in context

It is important to point out that comparing narrative identity accounts and popular narratives conflates two different understandings of 'narrative'. We might think that *narratives* are insufficient for the kinds of narrative portrayed by Altshuler and Korsgaard. Such narratives then are not controlling in the way Laybourn argues that they are.

Although narrative offers promise, it is also not clear how we might recognize a narrative in the wild, what does a sample narrative look like? Focusing on the expressions of regret in some popular songs may provide one answer. If some songs are narratives, the expressions of regret in them may provide a response to psychological and causal reductionism. As we saw earlier, love songs or anti-love songs can express regret for when the relationship ends, or regret for the relationship not ending sooner; which is another way for thinking about how the narrator's life may have gone differently.

What is important about the expression of the feeling of regret here, is what that experience does for the agent's behavior going forward in the context of the meaning that the narrative gives to that event, or the agent derives from it. Love songs could be a form of narrative thinking in both the philosophical context and the popular one. Importantly here however, love songs might be a process by which someone organizes their experience and creates their own identity [@sche96b].

As such, the second kind of question is a question about what we believe to be true about ourselves. Related to this then is a question about what extent do our environments contribute to our beliefs about what is true about ourselves, including our moral and other obligations. Here I suggest then that how we should understand such questions, who we are, is in the form of narrative regrets. How we should understand art then, is as a way of exploring expressions of narrative regret.

Even more important for our context of identity, this narrative thinking is always done in the context of self-other relationships. As such, the emotion of love is important, and regret is important for understanding the importance of love for self-identity. Without this particularly self-other relational thinking rooted in love, it is difficult for the victim to develop an authentic understanding of who she is.

## Regret and Other Popular Music Forms

It is possible that when a song expresses regret for not having met someone sooner, they are thinking about how their life might have gone had they married sooner. The marriage itself is not meaningful for the individual as a stand-alone event. Rather, the marriage only has causal influence on the subsequent events of that person's life and it is the person who defines the event in such a way to make it a meaningful marker of their own identity. It is where the marriage sits in the overall context of the course of a given relationship for instance. A marriage event in the context of a short and harmful relationship has a very different meaning than one in the context of a long and loving relationship. Most importantly however, it is important in the context of the meaning that a person derives from the event.

Many popular songs are saturated in the emotion of regret. In such contexts, the narrative expresses a negative emotion in response to something a character in the narration did, or that was done to them.

In *The Grand Tour*, the narrator as character expresses regret at having lost a significant other while the song *He Stopped Loving Her Today*, the narrator, giving a narrative account of someone else also expresses the regret felt by the character when their relationship dissolves. The above are emblematic country songs in that regret is commonly expressed in country music. Different songs express regret in different contexts however. *Apologize* by Timbaland is not a country song, and expresses regret in a different context. Here the narrator expresses regret for the love that he, the narrator, *had* felt.

Love songs often express regret when a relationship ends. In the song *The Grand Tour*, our attention is drawn to the daily use of items "where she used to . . ." which speak to the fact that they were once shared by people who experienced positive sentiments toward one another. Their current state however suggests that they are no longer used this way ". . . this old house will never be the same . . .". In *The Grand Tour*, there is existing controversy over whether the end of the relationship is caused by the narrator, or someone else. In the podcast *Cocaine and Rhinestones: The history of country music*, Tyler Mahan Coe suggests that the change in the state of the lives of the individuals involved in *The Grand Tour* is the result of a tragic mishap citing these lines in the song; "There's her rings, all her things, and her clothes are in the closet" and "as you leave you'll see the nursery, . . . taking nothing but the baby and my heart".

The events in *The Grand Tour* may not have been caused by the involvement from any agent. For instance, if Coe is correct, then the dissolution of the relationship depicted in *The Grand Tour* has nothing to do with any actions committed on the part of the narrator or his lost love. In *He Stopped Loving Her Today*, the regret is more definitively caused by an action when the subject whom the song speaks about is left by their significant other effectively dissolving their relationship. "He said I'll love you 'till I die, She told him 'you'll forget in time'". Regret can be the result of either an action or an event and the regret in *The Grand Tour* is likely caused by an event, whereas in Jones' other song, *He Stopped Loving Her Today*, it is likely caused by an action for instance if the protagonist pursued undisclosed intimate relationships with others.

While in the two previous examples *regret* is expressed upon the end of a relationship or rather its dissolution, in other examples, more positive emotions, not regret, are expressed upon the end or dissolution of the relationship rather than of the relationship's continuance. For instance Kelly Clarkson's *Since U Been Gone* does this: "Since you've been gone, I can breath for the first time . . .". There are also different reasons for the regret whether expressed for having suffered through the ordeal of that relationship, or for its end. Sometimes the regret is expressed as a longing for various qualities the loved possessed, for instance in the *Grand Tour*, "over there, sits the chair ... and whisper 'oh I love you'". For these reasons, narratives can help us to feel closeness and union with those the loved even though they are fictional. This correlates with expressions of emotion associated with love, where love has often been defined as the feeling of loving emotions provoked in one party by another. Upon the object's absence, the subject no longer feels these emotions and experiences regret on account of this absence [@tayl76]. The lover can also experience regret in longing for the qualities not possessed by the loved, when someone whom they loved failed to reciprocate in word or deed, or failed in some other way. For instance in Timbaland's *Too Late to Apoplogize* the following line expresses this: "tell me that you need me then you go and cut me down".

At the center of the difference between popular narratives like those found in popular songs, and narrative identity accounts is that popular narratives are merely ones we are prompted to imagine [@gilm20, 132]. But the source of narrative identities is not clear. The question then is what connection do those narratives that we are prompted to imagine, have to our own narrative identities. John @gilm20 suggests that the relationship is weak and dependent on the function of the imagination for engaging with the work. Patricia Hill Collins and Wendy Laybourn on the other hand suggest a strong relationship [@coll06; @coll09; @layb18]. The narratives in popular media are controlling images designed to justify racist and sexist attitudes.

> Controlling images “are designed to make racism, sexism, poverty, and other forms of social injustice appear to be natural, normal, and inevitable parts of everyday life” [@coll09, 77].

It is important to point out here that I am not asking about purpose or the design of such prompted imaginings. Rather, focusing on Laybourn's context of 'authenticity' and 'realness' highlights a popular implicit assumption regarding what is true and what is fiction in popular media. Peter @gold09 highlights our emotions as a form of reflection, especially that of regret. Sometimes as agents, the expressions of regret enables one to better exercise their own agency. We can imagine someone being cheated through the purchase of a used car. Looking towards the future, that individual would exercise more caution as a consequence upon reflection of their mistake. In these moments, the ability to tell a story becomes important as we are enabled by the narrative to recognize the appropriate objects of our emotions in the story. Reflecting on the failed used car purchase, the subject experiences regret. This subsequent experience pushes them to exercise more caution in the future. Similarly, we can compare this to another example. Here, regret is either appropriate to aspects of the story which bear no direct relation on the narrator, or ones that do. Being able to recognize and reflect on emotions enables one to express their agency going forward. What regret is afforded to the subject when reflecting on decisions made by themselves?

In this context, narrative is substantial in our lives as it provides ways of thinking about how our lives may have gone differently, or may go differently and why; our plans for the future and how things might turn out.^[For contrast, see Michael @brat00 argues that as agents, we are purposeful and reflective about our motivations, and capable of organizing our activity over and in-line with our purposes and motivations as we reflect on them. One method of reflection involves the expressions of various emotions upon the occurrence of some event.] Thinking in this way leads to regret if we are disappointed in a particular choice we have made. Our feelings of regret can cause us to behave differently in the future. Questions about narrative thinking then just are questions about moral agency.

Importantly, the possible prospect of being able to imagine today what a morally good life will look like for us tomorrow, is a question about how what we believe about ourselves today, including what desires we have, influence our ability to pursue these ways of being. These in turn determine our regrets. Imagining what kind of person our spouse will be can perhaps open up some romantic possibilities while closing others. Imagining where we will buy our first home may restrict our career choices, just like imagining how many children we will have may affect where we want to live. But more importantly, having various beliefs about ourselves undergird all these other possibilities.

More importantly, we can develop a sense of agency when we imagine ways in which our friendships, family ties, and other important relationships will go. These are preceded by beliefs in us about ways they *could* go. We can imagine the type of person we are to others and take needed steps for becoming that person, if we believe it is possible. As such, the person we will be and how we will relate to others is the goal that is formed by a narrative. Consider one particular narrative, we imagine ourselves as thoughtful, kind, considerate, loving, or compassionate. Imagining ourselves this way becomes the motivation we need to read up on the latest parenting methods. We might imagine ourselves being invited to witness the birth of a friend's first child and scour the internet for advice on how to be a better gift giver.

While the argument that the way we imagine our lives going can have a positive causal effect on the kind of person we become, one may argue that this view is too optimistic. To what extent do the experiences we have shape the person we become? For instance, Eric J. @mill20 argues that victimhood imposes normative standards that ground the moral status of the victim. What he means is that social roles, such as victim, determine the values we are expected to live by.

As a victim, there are various normative standards imposed on us that undermine our ability to imagine other parenting styles and values, such as those relating to how we protect and nourish our children. Libertarian values may be those we are less apt to promote in our homes. One reason is that when victims as parents, or the parents of victims, instruct a child, they must instruct them to act in self-subordinating ways "when confronted by the police" [221] rather than in ways that assert their autonomy.

Consider the following example narratives:

* Ty Dolla’s *by Yourself*: “Stacked your bread and bought your own Mercedes (Vroom, vroom). You your own boss, do it your way (Way)

The song's protagonist is faced with a given environment that forces her to exert her indepedence rather than her social bonds. As such, her lack of regret is a normative standard imposed on her. We can contrast this situation with the possibility that while material goods may or may not be a necessary condition for well-being, they are certainly not a sufficient one as expressed in other popular songs. The protagonist in the song *Rich and Sad* by Post Malone, looks back over other events, motives, and desires that resulted in the dissolution of his relationship and he feels sadness, as an expression of regret:

* “All this stuntin' couldn't satisfy my soul (–oul), Got a hundred big places, but I'm still alone (–one)”.

First, each of the above narratives are constrained by beliefs the narrator may have about themselves. In the first, the narrator, believing they have no other choice but to cut themselves off from anyone who is unable to contribute financially. But it does lead to another criticism, the agency of the artist versus that of the audience. Some music criticisms will often point out that musical taste assumes a sense of moral autonomy not available to some. If an artist is accustomed to abject poverty, then that person might be seen as vulnerable to market forces, creating art that is in high demand for the purposes of financial gain [@layb18], or only capable of representing their immediate physical environment [@rich02]. Regret within narratives are an example of such narrative agency. But if Eric Miller is correct, then some populations just do not possess agency in the requisite sense. But this view would thoroughly undermine decades of social justice movements in law and elsewhere.

The common responses to such criticisms come in two forms. They typically make some causal claim about the effects of environment on both artistic performance [@rich02], and audience music selection criteria, for instance, that artists are merely defining their personal experiences [@shus07, 419]. This responses highlight unequal wealth opportunities imposing normative standards on their victims. The second kind of response makes a cultural claim deriving from supposed traditional practices in pre-colonial Africa [@abra06].

Importantly here, the responses that are grounded in assertions about the culture of pre-colonial Africa are not necessarily a response to the empirical claims about the representations of anti-social behavior in rap and hip-hop music, but rather to the metaphorical use of language exhibited by pre-colonial African tribal practices. What are commonly noted as anti-social themes in rap and hip-hop then are downplayed as word-play underlying a cultural or political critique or something else entirely. Namely the references to violence and misogyny are allegorical, not literal [@smit97; @gate89]. What is important among these responses however, is that they too undermine attributions of personal identity and human agency and go against the dual character concept of art.

Separately, some have held that we can determine the values an artist holds, by carefully listening to the song lyrics they write. Although this fact would suggest that an artist's lyrics might qualify as a personal narrative defining an artist's identity and agency, it is not clear whether such narratives would qualify on this account of narrative agency. Although Altshuler's account could give more credence to music lyrics as an example narrative in the psychological sense, it is not clear how this may be the case. According to some accounts, an artist's written lyrics and musical arrangement merely express plausible values someone might hold [@malo18], while others articulate them as more definitive [@meis22a], still others argue that art is functional [@gilm20], thereby leaving open the possibility they could count as narrative in the functional sense, but do not do so necessarily.

It may be that rap and hip-hop are not good example narratives. But they show promise. Consider the question above, is some material good a necessary and sufficient condition for well-being as expressed in some popular songs? As narratives, the two examples above would better explain why some event happened. Why the protagonist in *by yourself* severed their relationship with their significant other, and why the protagonist in *Rich and Sad* is rich and sad.

Here, we primarily contrast [money] as the material object expressing that it:

* “could satisfy my soul”

And contrasting this with [money] as the material object expressing that it:

* “could not satisfy my soul”.

One way that narratives are thought to explain agency then, is by synchronizing incongruous events, states, and motives. As such, a narrative can say yes, money is either a necessary and sufficient condition for well-being for some agent or not. As such, the expressions of regret offers a plausible way to recognize the core of one's agency.

Recognizing the form of some plausible narratives may help to understand how to recognize a narrative if we say it. The various incidents and events have made it difficult for the agent to recognize value in non-material objects. We can, and often do, ask a meta-ethical question about what kinds of objects are truly of moral value and why. The narrative provides us with a plausible account of the why. For instance, we can ask to what extent the quest for consumer goods ought to outweigh other pursuits such as time with one's children or calling one's mother on Sunday. What is probably missing from the above is the understanding that there is a difference between only some material possession being necessary for well-being, versus some non-material possession being necessary for well-being.

But exactly how are material and non-material objects expressed over and against one another other? It may be the case that volunteering at an orphanage is of moral value and it can be expressed in song in at least two ways. Lyrically, "I wish I had volunteered at the orphanage yesterday". Or lyrically that expresses a negative outcome for not having volunteered at the orphanage yesterday. In constructing lyrics of the second form, the author chooses words that either have been historically encoded with the sentiment she is hoping to ascribe to a state of affairs, or is potentially encoded with that sentiment in such a way that the desired emotion is potentially ascribed to that state of affairs. However, if I neglect my children in volunteering at an orphanage, then *my* volunteering is of reduced moral value and we could imagine a lyrics saying "I wish I had spent time with my children instead of volunteering at the orphanage yesterday", or that says "I spent so many hours at the orphanage that I do not know who my own children are anymore"; or "I spent hours at the orphanage, I do not know who my own children are anymore".

We can also express a normative question about what behaviors are appropriate, when we should be kind, or whether a given action is more kind than another using similar methods. But there are additional interesting questions. As inferred above, we ask about the context in which a given ethical question is of moral value, and we can express it as a value by inviting the audience to reflect on such expressions by coercing their emotions accordingly. Volunteering my time at an orphanage is of moral value, and so I would use music or poetry to evoke emotions in the audience that correspond with this value. Considering the context is a way to assess the rationality of a given question, emotional expression in art is a way to make sense of that question. Making sense of the question helps us to anticipate the answer in at least two ways, what does the artist suggest is valuable, we would then look at the emotional expressions in her art, and what is the agent potentially capable of valuing.

For instance, assuming that Jill is the last sentient creature on a far away planet, it may not make sense to ask what Jill's ethical obligations are to those around her. But contexts regarding ethical questions are important. There are two important such contexts here; socio-economic or cultural environments, and psychological or social ones. Given questions about morality, our concerns are largely about how we should behave toward others. For many years, this was answered by referencing cultural and socio-economic conditions. More controversially, it has also been answered by referencing psychological or social conditions. But this is not the same as asking whether a given question about ethical obligation makes sense or not. It would not make sense to say a person with a medical condition that precludes the experience of empathy, has an ethical obligation to experience the emotions that align with empathy. There is a way in which our questions about moral behavior should make sense. This is in the context of our behavior toward others. Most humans, will generally live in contexts wherein our behavior to others should have a kind of rationality about them, in valuing our relationships with others.

The social version of this question is more opaque. It is a question about our social environments and to what extent our social environments can provide us with the resources necessary to fulfill our moral obligations. Once again, there are two categories of question here. For instance, consider our choices as to what kind of careers would make fulfilling our moral obligations possible. If we recognize a moral obligation to give vast amounts of wealth to charity, then we could pursue a set of social connections (work hard in high school and get into a good university) that would make our ability to fulfill this obligation more likely. The other category of question is even more difficult however. It begins as a question about ourselves and the sources of our beliefs as to what is possible, and what is not. We would start with a question about what is true about ourselves. Related to this is a question about what extent do those around us contribute to our beliefs about what is true about ourselves and what is obligatory in regard to our behavior. If we consider that we have a moral obligation to support national health, then there are some political parties we might campaign on behalf of and others we would not. Here I suggest then that how we should understand such questions is in the form of a narrative.

# Works Cited

<!-- This option seems to be more pleasing for rmarkdown::pdf_document() with my templates -->
<!-- \setlength{\parskip}{6pt} -->

<!-- If you're using bookdown, this seems to look better with bookdown::pdf_document2() -->
\setlength{\parskip}{8pt}
\setlength{\parindent}{-0.15in}
\setlength{\leftskip}{0.15in}
\vspace*{-0.35in}
\noindent
