# On Greek Tragedy

## Three Kinds of Tragic Conflict

1. Good people being ruined becuase of things that just happen to them, things they do not control.
2. Good people doing bad things, things opposite of their ethical character and commitments because of things they do not control.
3. Good people doing bad things without direct physical compulsion and opposite of their ethical character and commitments though done in light of circumstances of equally bad choices.

Agammenon is waiting on the shore with his entire fleet. He intends to carry out a directive from Zeus to avenge his brother whose wife ran away with Paris, prince of Troy. However, because of an earlier transgression against Artimis, Artimis is holding back the wind, stranding his fleet. Agammenon, as the result of an omen of an eagle devouring a hare, is told that in order to appease Artimis, he must sacrifice his daughter Iphigenia.

As such, Agammenon is faced with two impossible choices, fail to carry out Zeus's command, or kill his daughter. It is important to point out that the fleet is already facing starvation being stranded on the coast.

However, Agammenon's sin, is not that he choices sacrificing his daughter, instead it is the way he sacrificed his daughter.

* Like in the biblical story of Abraham, a good man must kill an innocent child "out of obedience to a divine command" [35].
* Agammenon's sin however, is not the choice, but rather how the choice was made:
  * Agammenon now begins to cooperate inwardly with necessity, arragning his feelings to accord with his fortune.
  * From the moment he makes his decision, itself the best he could have made, he strangely turns himself into a collaborator, a willing victim [35].

Progression of loss of agency:

* Necessity of the act
* to the rightness of the act
* to the rightness of the feelings of the act
