# The Virtue of Luck (a reading of luck and ethics from Fragility of Goodness)

What is the relationship between human virtue and environmental variables? In order for a trait to be the virtue of a human being, some would like to say that it has to represent choices, rationality, actions, beliefs. However, often times these depend on environmental variables which we do not control. Most importantly among these are the values that we hold dear to us. Whether or not we recognize the importance of close relationships for instance. However, if the luck question is accurate, even these values depend on factors that are outside of our control. Our fragility, need for loved ones, friendship, etc., can at one time depend on whether or not we've encountered sufficient hardships for instance, but even outside the experience of hardships, friendships, which are also external and an environmental variable at once hold intrinsic importance, although these are external to us. As such "human goodness is nourished, even constituted, by external happenings". [1-2]
