# Annotations
(3/1/2026, 10:47:30 PM)

“I then argue for an alternative view of authentic work performance that combines the best of Dodd’s and Davies’s ideas: an authentic performance is one that aims to evince understanding of the work through complying fully with its score.” ([Kania, 2025, p. 128](zotero://select/library/items/KLTTRVLX)) ([pdf](zotero://open-pdf/library/items/NVKHAI3N?page=1&annotation=PW42IX3M))

“According to Davies, “authentic” simply means something like genuine, so that an authentic performance is a genuine instance of the work.” ([Kania, 2025, p. 128](zotero://select/library/items/KLTTRVLX)) ([pdf](zotero://open-pdf/library/items/NVKHAI3N?page=1&annotation=UY9VZEXQ))

“A theory of authentic performance thus requires an account of both what a work is, and the relationship between a work and its performances.2” ([Kania, 2025, p. 128](zotero://select/library/items/KLTTRVLX)) ([pdf](zotero://open-pdf/library/items/NVKHAI3N?page=1&annotation=NKCAC2XG))

A musical work is created in the process of producing an authorized score, regardless of what a musical work is. A recording is a performance.

“As for the relationship between a musical work and its instances, Davies argues that three necessary and jointly sufficient conditions must be met by any instance of a scored classical work:” ([Kania, 2025, p. 128](zotero://select/library/items/KLTTRVLX)) ([pdf](zotero://open-pdf/library/items/NVKHAI3N?page=1&annotation=S4QR9TC6))

“(2) the performers must intend to follow (most of) the instructions specifying the work ...;” ([Kania, 2025, p. 128](zotero://select/library/items/KLTTRVLX)) ([pdf](zotero://open-pdf/library/items/NVKHAI3N?page=1&annotation=DDQD76BI))

“[and] (3) there must be a robust causal chain from the performance to the work’s creation, so that the matching achieved is systematically responsive to the composer’s work-determinative decisions” (S. Davies 2001, 182).” ([Kania, 2025, p. 128](zotero://select/library/items/KLTTRVLX)) ([pdf](zotero://open-pdf/library/items/NVKHAI3N?page=1&annotation=BAUK52L2))

“One obligation is to follow the score of the work in performing it; the other is to communicate a significant part or aspect of the work’s meaning.4” ([Kania, 2025, p. 129](zotero://select/library/items/KLTTRVLX)) ([pdf](zotero://open-pdf/library/items/NVKHAI3N?page=2&annotation=YMKI8WAF))

“As he puts it, “interpretive authenticity trumps score compliance authenticity” (147).” ([Kania, 2025, p. 129](zotero://select/library/items/KLTTRVLX)) ([pdf](zotero://open-pdf/library/items/NVKHAI3N?page=2&annotation=U8I9PPDJ))

“I believe that Dodd has misunderstood the role of scores in the practice and lost sight of the importance of the musical details to a work’s meaning. What we need is a theory that acknowledges the centrality of the work as scored to both its meaning and its authentic performance.” ([Kania, 2025, p. 129](zotero://select/library/items/KLTTRVLX)) ([pdf](zotero://open-pdf/library/items/NVKHAI3N?page=2&annotation=YSDPWPPT))

[“I am interested in philosophical issues presented by reconstructions of ballet classics, especially those from the nine](zotero://note/u/WF9QF6Q8/)
