# Patricia Collins Black Feminist Thought

<<<<<<< HEAD
::: {#collins-knowledge-power}

In the 2009 version of Collin's book "Black Feminist Thought", Collins draws greater emphasis between relationships of knowledge and power.
=======
In the 2009 version of Collin's Black Feminist Thought, BFT, Collins draws greater emphasis between relationships of knowledge and power. It is often said
>>>>>>> c01c36720c0ed9ab1fa8147e745afbc831d07ac1

* that knowledge = power,

but a worrying theme throughout the book, is that this is wrong and that rather

* power = knowledge.

One might notice the misapplication of a logical principle here, because whenever we use the equals sign, there is not a logical difference between power = knowledge and knowledge = power.

> Rather, this says that power is identical in value to knowledge and if power is identical to knowledge, then knowledge is identical to power.

In other words, the initial application claims that the direction of fit is not directional but rather than uni- or bi-directional.

For instance, we could look at some possible relationships between knowledge and power below:

* knowledge $\rightarrow$ power

or

* power $\rightarrow$ knowledge

or

* knowledge $\leftrightarrow$ power

Initially, we might think that assuming that if one has knowledge then the correct state of affairs should be that they will fulfill their aims, whatever those may be. This is often a selling point for higher education.

<<<<<<< HEAD
:::

::: {#collins-struggle}

This is a common position in what is lauded as "African American Studies". Often times these positions are wrapped in the language of "struggle". While Collins notes that this "struggle" is a struggle for empowerment, it is not particularly clear who the struggle is directed at. She argues that the struggle is global and transcendent, and she defines it as one for "survival." But she expands the target in the most recent edition of her book to include recent developments in the areas of sexuality and "sexual politics" of black womanhood.

:::

The books target initially then is "black" empowerment which would involve the acquisition of knowledge. The problem with the above however, is that any correlation between knowledge and power is wrong from a Christian world view. Rather one is grounded in power if they have humility. "The fear of the Lord is the beginning of wisdom." Collins mentions the 19th century black feminist scholar Maria Stewart, noting that she urged self-reliance and independence and that her work was suppressed along with many other black feminist scholars of the era. However, we as a society know a lot more about the importance of community and inter-personal relationships, a fact which Stewart herself draws attention to:
=======
This is a common position in what is lauded as "African American Studies". Often times these positions are wrapped in the language of "struggle". While Collins notes that this "struggle" is a struggle for empowerment, it is not particularly clear who the struggle is directed at. She argues that the struggle is global and transcendent, she defines the struggle as one for "survival." But she expands the target in this edition to include recent developments of sexuality and "sexual politics" of black womanhood.

The problem with the above however, is that any correlation between knowledge and power is wrong from a Christian world view. Rather one is grounded in power if they have humility. "The fear of the Lord is the beginning of wisdom." Here, the implication is not on knowledge, knowledge without wisdom is useless and a fool's errand, it does not lead to "empowerment". Collins mentions the 19th century black feminist scholar Maria Stewart, noting that she urged self-reliance and independence and that her work was suppressed along with many other black feminist scholars of the era. However, we as a society know a lot more about the importance of community and inter-personal relationships, a fact which Stewart herself draws attention to:
>>>>>>> c01c36720c0ed9ab1fa8147e745afbc831d07ac1

> You have souls committed to your charge. . . . It is you that must create in the minds of your little girls and boys a thirst for knowledge, the love of virtue, . . . and the cultivation of a pure heart.
