### The Imago Dei Paradox

1. According to the Orthodox Christian position, God is ontologically distinct from creation.
2. Therefore God created humanity to establish an earthly image of Himself in the world.
3. Therefore humanity is bound to God and God's purposes for creation.
4. But since God created humanity, humanity is a part of his creation.
5. Therefore God is ontologically distinct from humanity.
6. Therefore God cannot use humanity to establish an earthly image of Himself in the world.
7. Therefore humanity is not an earthly image of God in the world.
8. (Some other implications) Therefore humanity is not bound to God and God's purposes for creation.

The Imago Dei as Human Identity is a book by Ryan Peterson which provides a response to premise 5 of the imago dei paradox. It's conclusion is that God is not ontologically distinct from humanity.

But it could also conclude a new understanding of "ontologically".

Or a different understanding of "creation" as it concerns human beings. Ultimately, there is a concern of the difference between:

* God created humanity
* God is distinct from creation

