## The Imago Dei Paradox

* Imago Dei is "humanity's identity"
  * basic to all human existence

1. According to the Orthodox Christian position, God is distinct from creation.
2. Therefore God created humanity to establish an earthly image of Himself in the world.
3. Therefore humanity is bound to God and God's purposes for creation.
4. But since God created humanity, humanity is a part of his creation.
5. Therefore God is ontologically distinct from humanity.
6. Therefore God cannot use humanity to establish an earthly image of Himself in the world.

### Some attempts to solve the paradox

1. Clines: Old testament studies should be used to correct pre-modern, dogmatic treatments of imago Dei.
   1. What did the human author of Genesis mean?
   2. Man is like God in some degree.
   3. However, Clines invokes new testament conceptions of imago Dei: image of God is Christ, the last (not the first), Adam.
2. Gray: New testament studies should be used, imago Dei means personhood.
   1. man as imago Dei represents Iranean concept: glory to glory (personal identity), progressively nearer to God (personhood).
   2. Human beings accountable to God for behavior (personhood and identity) since God is basis for relationship humans have with God.
   3. However, 2 represents two possibly unrelated claims: personal identity, personal transformation over the period of one's life (humanity transcends creation, no longer humanity).
   4. So it is not clear how image of God can be interpreted as personhood.
3. Colin Gunton
   1. Divine intra-Trinitarian relations = personshood: "freedom to be other and yet to stand in intimate communion is a created metaphor of God's intra-Trinitarian life" (life of Christ).
   2. imago Dei = whole person, looks to God for constructive understanding of the image, holds together both identity and transformation.
   3. However conflates between divine Persons and created relations between human persons.
4. Watson, relational interpretation but with Christological, Christ teaches us what it means to be human.
   1. But, not clear that can use Genesis 1 by itself
   2. (personhood and identity). Not sufficiently critical of artificial interpretive limits imposed by contemporary OT studies, does not realize dogmatic insights?
5. Ian McFarland, image conveys knowledge of the thing imaged, imago Dei delivers knowledge of God not of humanity.
   1. How we know about God from image, Christ
   2. What we know about God, Christ
   3. But how does imago Dei connect to Genesis 1? Collapses God to humanity, rather than elevate humanity to God?
