# Annotations
(2/28/2026, 5:12:03 PM)

“I am interested in philosophical issues presented by reconstructions of ballet classics, especially those from the nineteenth century” ([Van Camp, p. 1](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=1&annotation=JJ2R9DS5))

“I am interested in considering how contemporary audiences appreciate these reconstructions and what they seem to consider “authentic.”” ([Van Camp, p. 1](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=1&annotation=8GEZQZPG))

“Traditionally, in dance, choreography is handed down from dancer to dancer in the studio, but we have to wonder if the “telephone game” plays a part in altering those transmissions.” ([Van Camp, p. 2](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=2&annotation=V9FZRW92))

“I also am interested in comparing our understanding of “reconstruction” in dance with a more recent concept that has appeared in the literature, viz., “reenactment.”” ([Van Camp, p. 2](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=2&annotation=U7UYDLVJ))

“The philosophical dialogue centers on whether additional things must be present for authenticity.” ([Van Camp, p. 3](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=3&annotation=UXLL8JQH))

“In the absence of a comparable score for historic ballets, what approaches are available for understanding authenticity and accuracy in reconstruction?” ([Van Camp, p. 3](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=3&annotation=ZAV6TUYN))

“But in dance, there has not been a yearning to recreate what nineteenth century bodies were like.” ([Van Camp, p. 4](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=4&annotation=KMPQCKPR))

“This creates a problem for acceptance of today’s reconstructions, as audiences find they miss the later revisions which take advantage of those improved physical possibilities.” ([Van Camp, p. 4](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=4&annotation=DPJJB487))

“Because of these factors, it is understandable that our standards for reconstruction of twentieth-century works are substantially different from those for the nineteenth-century classics.” ([Van Camp, p. 5](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=5&annotation=XBW9MSLJ))

“My focus today is considering whether and why the dance community accepts these nineteenth reconstructions as authentic and historically accurate.” ([Van Camp, p. 5](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=5&annotation=52UZR466))

“His approach, like that of reenactments, rejects the sense that reconstructions are merely historic museums.” ([Van Camp, p. 5](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=5&annotation=GBZ5GX7F))

“With all these changes, though, might it make more sense to consider this just another reading of a classic none of us will ever see?” ([Van Camp, p. 6](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=6&annotation=68TTS28F))

“While interesting to curious aficionados, it is not overall as aesthetically appealing to audiences.” ([Van Camp, p. 7](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=7&annotation=GLJVYXBQ)) It appears as though there is a difference between historically appealing to audiences and aesthetically appealing to audiences.

“These changes would make the reconstruction less “authentic,” but presumably more aesthetically attractive to contemporary audiences.15” ([Van Camp, p. 7](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=7&annotation=ZE2HQSZK))

“So, in sum, Ratmansky’s reconstruction seems to count as authentic as it uses much of the original choreography (as far as we know from the limited record), the same score, a similar style of costumes, the same libretto, and mime passages.” ([Van Camp, p. 7](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=7&annotation=MVV4XFAR))

“The dance community seems to have accepted this version as the closest we are likely to get for this ballet.” ([Van Camp, p. 7](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=7&annotation=27XHSMBQ))

“That production was reportedly a spectacular failure and Tchaikovsky went to his grave blaming himself.” ([Van Camp, p. 7](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=7&annotation=GK88E9JQ))

“The version that has come down to us with numerous variations was made at the Mariinsky in 1895 by Marius Petipa and his assistant Lev Ivanov.” ([Van Camp, p. 7](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=7&annotation=SUF457TQ))

“So we do have this “baseline,” as it were, for choreography and music.” ([Van Camp, p. 8](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=8&annotation=5R4BJ739))

“In other ways, the reconstruction is a disappointment by contemporary expectations.” ([Van Camp, p. 8](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=8&annotation=B6V4HWHT))

“How has the reconstruction been received by today’s audiences? The results are mixed. Zurich, with a new artistic director, quietly dropped the reconstruction from its repertoire.” ([Van Camp, p. 9](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=9&annotation=EYSLQYAA))

“The Ratmansky reconstruction is of great interest to afficionados and historians to see what the ballet probably looked like to Russian audiences long ago.” ([Van Camp, p. 9](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=9&annotation=K4H25TLJ))

“But aesthetically, it is, in many ways, a disappointment.” ([Van Camp, p. 9](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=9&annotation=DC57WKRB))

“Perhaps most importantly, dancers today are much stronger and capable of more athletic feats than they were long ago. Risky overhead lifts and extreme extensions are missing, although we do see the famous 32 fouettes in Act III, which were in the original.” ([Van Camp, p. 9](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=9&annotation=EDX385GK))

“So Ratmansky choreographed this passage in what he considered a consistent style. Is it authentic? We have no way of knowing.23” ([Van Camp, p. 11](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=11&annotation=NCGMRST3)) Could it be that one reason in which the historisity is not particularly important is because we have no way of knowing?

“Where does this leave us? For all three ballets considered today, we have the musical score as a grounding for identity and an element of authenticity.” ([Van Camp, p. 11](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=11&annotation=7PBMR7XF))

“Dance audiences hungry to know what originals looked like tolerate giving those reconstructors considerable” ([Van Camp, p. 11](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=11&annotation=BQSTKK7T))

“license, mainly because we have no choice.” ([Van Camp, p. 12](zotero://select/library/items/IX66SVXD)) ([pdf](zotero://open-pdf/library/items/6UEPRSB4?page=12&annotation=TTI2XSEV))
