# Typecasts, Tokens, and Spokespersons

* Harmful credibility excess
  * harms its targets as knowers
  * and transmitters of knowledge
* Positive stereotyping and prejudicially inflated credibility assessments contribute to continued epistemic oppression
* Epistemic harms arising from prejudicially inflated assessments of their credibility.

## What kind of harm?

* harms its targets as knowers
* and transmitters of knowledge

### Respect

* harm which deprives speaker of basic Respect

* Respect == Not a full object
  * Pohlhaus 2014, 105 "Speaker assumes a sort of 'truncated' or 'circumscribed' Subjectivity
  * Beauvoir 1952, status as the 'other'

> relegated to the role of epistemic other, being treated as though the range of one's subject capacities is merely derivative [Pohlhaus 2014, 107]

* Subject are reduced to attending only to that which stems from the perpetrator's subjectivity

### Epistemic "derivatization" -> Compulsory Representation -> Unique form of Epistemic Exclusion

> the others capacities as a subject are reduced to attending only to that which stems from the perpetrator's subjectivity, so that anything the victim might try to express that exceeds the range of the perpetrator's subjectivity is actively prohibited and /or left unrecognized by the perpetrator, even while he recognizes the victim as capable of having experiences, interests, and desires. [106]

Therefore: not seen as "capable of contributing to epistemic practices uniquely, that is, from her own distinct lived experiences . . . she is not permitted to contribute in ways that extend beyond or trouble the veracity of the dominantly experienced world" [107]

* But, what about ***only*** *being seen as* "capable of contributing to epistemic practices uniquely, that is, from her own distinct lived experiences" 

[i.e., not through an ability to reason inferensially to a unique, non-normative conclusion] 

* and therefore, . . . "she is not permitted to contribute in ways that extend beyond or trouble the veracity of the dominantly experienced world"

A unique epistemic practice is one that is only subjectively true grounded not in universal experience, but subjective one.

> The problem with PCE is not that one is not permitted to contribute in ways that are perceived to extend beyond dominant experiences; rather, the problem is that one is only permitted (and expected to) contribute in ways that are considered "unique" and "distinct". [Davis 490]
