# Black authenticity and commodified realness: effects of controlling images and colourism

> Controlling images “are designed to make racism, sexism, poverty, and other forms of social injustice appear to be natural, normal, and inevitable parts of everyday life” (Collins 2000, 77).

* What are the purposes of controlling images?
* But if we broaden the label, then controlling images are designed to justify marginalizing some members of society.

# Cultural production in context: the case of rap music

> White corporate owners capitalized on the realness and rawness of rap music and used the artists’ and music’s authenticity as a marketing strategy. [@layb20]

* This process was finalized with mainstream consumption in the 1990s with the 1996 Telecommunications act
  * radio stations were consolidated from locally independent radio stations and labels to national conglomerates.
  * music labels were consolidated from locally independent music labels to national conglomerates.
* This meant that radio airplay format and songs were standardized.
* Additionally, the markets which justified these consoladations where 60-80% white [Bialik, Carl. 2005. “Is the Conventional Wisdom Correct in Measuring Hip-Hop Audience?” Wall Street Journal, May 5. Accessed May 1, 2013. http://online.wsj. com/news/articles/SB111521814339424546; Kitwana, Bakari. 2002. The Hip Hop Generation: Young Blacks and the Crises in African American Culture. New York: Basic Civitas Books.; Rose, Tricia. 2008. The Hip Hop Wars: What We Talk about When We Talk about Hip Hop And Why It Matters. New York: Basic Books.].

* Artists on their part began to equate 'artist legitimacy' with 'commercial success' [Lena, Jennifer C. 2006. “Social Context and Musical Content: Rap Music, 1979-1995.” Social Forces 85 (1): 479–495.].
* As a result, these artists started to sell stereotypical beliefs about blackness back to a consumer base.

# Hypotheses

