# Piecing Passions Apart

## Elements of Emotions

## Theories of Emotions

* James-lange
* Somatic feeling theory
* Somatic theory of emotion
* behavioral theory
* behavioral conditioning theory
* categorization Studies
  * internal systems of categorizatin, memory, attention, and reasoning interact with emotions in systematic ways.
    * It is easier to recall events when in emotions states that are congruent with events we are recalling (Bower 1981)
    * Positive emotions 
      * promote use of stereotypes (Bless, Schwarz, and Kemmelmeier 1996) 
      * and reason in ways that are open-minded, optimistic, and creative.
      * Easier time solving problems which require novel applications of familiar materials (Isen, Daubman, & Nowicki, 1987)
    * Negative emotions
      * promote more narrow attentional focus.
      * anxiety makes us attend to threatening objects (MacLeod & Mathews, 1991; Ohman, Flykt, & Esteves, 2001)
      * Sadness makes us more sensitive to our flaws.

## Hybrid Theories

## Dimensional Appraisal Theories

## *The Problem of Plenty*

> . . . how many parts of an emotion hang together.

* Either the components that make an emotion are separable or inseparable
